apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: mongodb
  labels:
    kubernetes.io/metadata.name: mongodb
  annotations:
    openshift.io/display-name: "MongoDB Operator Environment"
    openshift.io/description: "Namespace for deploying MongoDB Controllers for Kubernetes 1.2.0"
