apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
  namespace: mongodb
  annotations:
    mongodb.com/v1.architecture: "static"
spec:
  type: ReplicaSet
  members: 3
  version: "8.0.12-ent"
  opsManager:
    configMapRef:
      name: my-project
  credentials: organization-secret
  security:
    certsSecretPrefix: mdb
    authentication:
      enabled: true
      modes:
      - X509
    tls:
      ca: ca-issuer
      enabled: true